CREATE TABLE `Mood` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL
);

CREATE TABLE `Tag` (
    `id`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `subject`    TEXT NOT NULL
);

CREATE TABLE `Entry` (
	`id`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`datetime`  TIMESTAMP NOT NULL,
	`content` TEXT NOT NULL,
	`tag` TEXT NOT NULL,
	`mood` INTEGER NOT NULL,
	FOREIGN KEY(`tag`) REFERENCES `Tag`(`id`),
	FOREIGN KEY(`mood`) REFERENCES `Mood`(`id`)
);


DROP TABLE Mood;
DROP TABLE Tag;
DROP TABLE Entry;